sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t irostub/docker-react-app -f %cd%/03-docker-react-app/Dockerfile.dev ./03-docker-react-app

script:
  - docker run -e CI=true irostub/docker-react-app npm run test -- --coverage

after_success:
  - echo "test success"
